import type { Patient } from "@/types/patient"

export const samplePatients: Patient[] = [
  {
    id: "P-1001",
    age: 62,
    gender: "Female",
    condition: "Diabetes",
    bp_sys: 142,
    bp_dia: 88,
    hr: 78,
    bmi: 31.2,
    spO2: 96,
    hba1c: 8.1,
    cholesterol: 210,
    creatinine: 1.0,
    med_adherence_percent: 72,
    last_update: "2025-08-01",
    riskScore: 61,
    riskLevel: "Medium",
    drivers: ["HbA1c elevated at 8.1", "Adherence modest at 72%"],
    medications: "Metformin",
  },
  {
    id: "P-1002",
    age: 68,
    gender: "Male",
    condition: "Heart Failure",
    bp_sys: 150,
    bp_dia: 94,
    hr: 84,
    bmi: 29.1,
    spO2: 92,
    hba1c: 6.7,
    cholesterol: 235,
    creatinine: 1.3,
    med_adherence_percent: 58,
    last_update: "2025-08-02",
    riskScore: 78,
    riskLevel: "High",
    drivers: ["Adherence low at 58%", "SpO2 reduced at 92%", "Cholesterol high at 235"],
    medications: "Furosemide, ACE inhibitor",
  },
  {
    id: "P-1003",
    age: 55,
    gender: "Female",
    condition: "CKD",
    bp_sys: 130,
    bp_dia: 82,
    hr: 70,
    bmi: 27.5,
    spO2: 98,
    hba1c: 6.1,
    cholesterol: 180,
    creatinine: 1.6,
    med_adherence_percent: 90,
    last_update: "2025-08-03",
    riskScore: 32,
    riskLevel: "Low",
    drivers: ["Creatinine slightly high at 1.6"],
    medications: "ARB",
  },
]
